// Copyright 2015 The gRPC Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// The canonical version of this proto can be found at
// https://github.com/grpc/grpc-proto/blob/master/grpc/health/v1/health.proto

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: grpc/health/v1/health.proto

package healthconnect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	health "github.com/pbrpc/connect-protos/health"
	sync "sync"
)

const (
	// HealthName is the fully-qualified name of the Health service.
	HealthName = "grpc.health.v1.Health"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthCheckProcedure is the procedure name of the Health's Check RPC.
	HealthCheckProcedure = "/grpc.health.v1.Health/Check"
	// HealthListProcedure is the procedure name of the Health's List RPC.
	HealthListProcedure = "/grpc.health.v1.Health/List"
	// HealthWatchProcedure is the procedure name of the Health's Watch RPC.
	HealthWatchProcedure = "/grpc.health.v1.Health/Watch"
)

var (
	healthCheckSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     health.File_grpc_health_v1_health_proto.Services().ByName("Health").Methods().ByName("Check"),
			Procedure:  HealthCheckProcedure,
		}
	})
	healthListSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     health.File_grpc_health_v1_health_proto.Services().ByName("Health").Methods().ByName("List"),
			Procedure:  HealthListProcedure,
		}
	})
	healthWatchSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeServer,
			Schema:     health.File_grpc_health_v1_health_proto.Services().ByName("Health").Methods().ByName("Watch"),
			Procedure:  HealthWatchProcedure,
		}
	})
)

// HealthClient is a client for the grpc.health.v1.Health service.
type HealthClient interface {
	// Check gets the health of the specified service. If the requested service
	// is unknown, the call will fail with status NOT_FOUND. If the caller does
	// not specify a service name, the server should respond with its overall
	// health status.
	//
	// Clients should set a deadline when calling Check, and can declare the
	// server unhealthy if they do not receive a timely response.
	Check(context.Context, *health.HealthCheckRequest) (*health.HealthCheckResponse, error)
	// List provides a non-atomic snapshot of the health of all the available
	// services.
	//
	// The server may respond with a RESOURCE_EXHAUSTED error if too many services
	// exist.
	//
	// Clients should set a deadline when calling List, and can declare the server
	// unhealthy if they do not receive a timely response.
	//
	// Clients should keep in mind that the list of health services exposed by an
	// application can change over the lifetime of the process.
	List(context.Context, *health.HealthListRequest) (*health.HealthListResponse, error)
	// Performs a watch for the serving status of the requested service.
	// The server will immediately send back a message indicating the current
	// serving status.  It will then subsequently send a new message whenever
	// the service's serving status changes.
	//
	// If the requested service is unknown when the call is received, the
	// server will send a message setting the serving status to
	// SERVICE_UNKNOWN but will *not* terminate the call.  If at some
	// future point, the serving status of the service becomes known, the
	// server will send a new message with the service's serving status.
	//
	// If the call terminates with status UNIMPLEMENTED, then clients
	// should assume this method is not supported and should not retry the
	// call.  If the call terminates with any other status (including OK),
	// clients should retry the call with appropriate exponential backoff.
	Watch(context.Context, *health.HealthCheckRequest) (HealthWatchClientStream, error)
}

// NewHealthClient constructs a client for the grpc.health.v1.Health service. Multiple service
// clients may share a single connect.Client.
func NewHealthClient(client *connect.Client) HealthClient {
	return &healthClient{client: client}
}

// HealthWatchClientStream is the client stream for the Health's Watch RPC.
type HealthWatchClientStream struct {
	stream connect.ClientStream
}

// Receive returns the next response message from the server.
func (s HealthWatchClientStream) Receive() (*health.HealthCheckResponse, error) {
	var res health.HealthCheckResponse
	if err := s.stream.Receive(&res); err != nil {
		return nil, err
	}
	return &res, nil
}

// Close releases the stream's resources. It is idempotent and is typically deferred to clean up a
// stream abandoned before io.EOF.
func (s HealthWatchClientStream) Close() error {
	return s.stream.Close()
}

// HealthHandler is an implementation of the grpc.health.v1.Health service.
type HealthHandler interface {
	// Check gets the health of the specified service. If the requested service
	// is unknown, the call will fail with status NOT_FOUND. If the caller does
	// not specify a service name, the server should respond with its overall
	// health status.
	//
	// Clients should set a deadline when calling Check, and can declare the
	// server unhealthy if they do not receive a timely response.
	Check(context.Context, *health.HealthCheckRequest) (*health.HealthCheckResponse, error)
	// List provides a non-atomic snapshot of the health of all the available
	// services.
	//
	// The server may respond with a RESOURCE_EXHAUSTED error if too many services
	// exist.
	//
	// Clients should set a deadline when calling List, and can declare the server
	// unhealthy if they do not receive a timely response.
	//
	// Clients should keep in mind that the list of health services exposed by an
	// application can change over the lifetime of the process.
	List(context.Context, *health.HealthListRequest) (*health.HealthListResponse, error)
	// Performs a watch for the serving status of the requested service.
	// The server will immediately send back a message indicating the current
	// serving status.  It will then subsequently send a new message whenever
	// the service's serving status changes.
	//
	// If the requested service is unknown when the call is received, the
	// server will send a message setting the serving status to
	// SERVICE_UNKNOWN but will *not* terminate the call.  If at some
	// future point, the serving status of the service becomes known, the
	// server will send a new message with the service's serving status.
	//
	// If the call terminates with status UNIMPLEMENTED, then clients
	// should assume this method is not supported and should not retry the
	// call.  If the call terminates with any other status (including OK),
	// clients should retry the call with appropriate exponential backoff.
	Watch(context.Context, *health.HealthCheckRequest, HealthWatchServerStream) error
}

// RegisterHealthHandler registers svc as the grpc.health.v1.Health implementation on server.
func RegisterHealthHandler(server *connect.Server, svc HealthHandler) {
	adapter := healthHandler{svc: svc}
	server.Register(
		connect.Method{Spec: healthCheckSpec(), Handler: adapter.check},
		connect.Method{Spec: healthListSpec(), Handler: adapter.list},
		connect.Method{Spec: healthWatchSpec(), Handler: adapter.watch},
	)
}

// HealthWatchServerStream is the server stream for the Health's Watch RPC.
type HealthWatchServerStream struct {
	stream connect.ServerStream
}

// SendHeaders flushes the response headers without a message. The first Send does this implicitly.
func (s HealthWatchServerStream) SendHeaders() error {
	return s.stream.SendHeaders()
}

// Send sends a response message to the client.
func (s HealthWatchServerStream) Send(res *health.HealthCheckResponse) error {
	return s.stream.Send(res)
}

// UnimplementedHealthHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthHandler struct{}

func (UnimplementedHealthHandler) Check(context.Context, *health.HealthCheckRequest) (*health.HealthCheckResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "grpc.health.v1.Health.Check is not implemented")
}

func (UnimplementedHealthHandler) List(context.Context, *health.HealthListRequest) (*health.HealthListResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "grpc.health.v1.Health.List is not implemented")
}

func (UnimplementedHealthHandler) Watch(context.Context, *health.HealthCheckRequest, HealthWatchServerStream) error {
	return connect.NewError(connect.CodeUnimplemented, "grpc.health.v1.Health.Watch is not implemented")
}

type healthClient struct {
	client *connect.Client
}

func (c *healthClient) Check(ctx context.Context, req *health.HealthCheckRequest) (*health.HealthCheckResponse, error) {
	var res health.HealthCheckResponse
	if err := c.client.CallUnary(ctx, healthCheckSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *healthClient) List(ctx context.Context, req *health.HealthListRequest) (*health.HealthListResponse, error) {
	var res health.HealthListResponse
	if err := c.client.CallUnary(ctx, healthListSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *healthClient) Watch(ctx context.Context, req *health.HealthCheckRequest) (HealthWatchClientStream, error) {
	stream, err := c.client.CallServerStream(ctx, healthWatchSpec(), req)
	if err != nil {
		return HealthWatchClientStream{}, err
	}
	return HealthWatchClientStream{stream: stream}, nil
}

type healthHandler struct{ svc HealthHandler }

func (h healthHandler) check(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req health.HealthCheckRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Check(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h healthHandler) list(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req health.HealthListRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.List(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h healthHandler) watch(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req health.HealthCheckRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	return h.svc.Watch(ctx, &req, HealthWatchServerStream{stream: stream})
}
