// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: info/info.proto

package infoconnect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	info "github.com/pbrpc/connect-protos/info"
	sync "sync"
)

const (
	// InfoServiceName is the fully-qualified name of the InfoService service.
	InfoServiceName = "info.InfoService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InfoServiceVersionProcedure is the procedure name of the InfoService's Version RPC.
	InfoServiceVersionProcedure = "/info.InfoService/Version"
)

var (
	infoServiceVersionSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     info.File_info_info_proto.Services().ByName("InfoService").Methods().ByName("Version"),
			Procedure:  InfoServiceVersionProcedure,
		}
	})
)

// InfoServiceClient is a client for the info.InfoService service.
type InfoServiceClient interface {
	// Version reports the running server's version.
	Version(context.Context, *info.VersionRequest) (*info.VersionResponse, error)
}

// NewInfoServiceClient constructs a client for the info.InfoService service. Multiple service
// clients may share a single connect.Client.
func NewInfoServiceClient(client *connect.Client) InfoServiceClient {
	return &infoServiceClient{client: client}
}

// InfoServiceHandler is an implementation of the info.InfoService service.
type InfoServiceHandler interface {
	// Version reports the running server's version.
	Version(context.Context, *info.VersionRequest) (*info.VersionResponse, error)
}

// RegisterInfoServiceHandler registers svc as the info.InfoService implementation on server.
func RegisterInfoServiceHandler(server *connect.Server, svc InfoServiceHandler) {
	adapter := infoServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: infoServiceVersionSpec(), Handler: adapter.version},
	)
}

// UnimplementedInfoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInfoServiceHandler struct{}

func (UnimplementedInfoServiceHandler) Version(context.Context, *info.VersionRequest) (*info.VersionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "info.InfoService.Version is not implemented")
}

type infoServiceClient struct {
	client *connect.Client
}

func (c *infoServiceClient) Version(ctx context.Context, req *info.VersionRequest) (*info.VersionResponse, error) {
	var res info.VersionResponse
	if err := c.client.CallUnary(ctx, infoServiceVersionSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type infoServiceHandler struct{ svc InfoServiceHandler }

func (h infoServiceHandler) version(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req info.VersionRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Version(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
