// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: admission/admission.proto

package admission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdmissionRequest is one request as the gateway received it.
type AdmissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request path, /package.Service/Method.
	Procedure string `protobuf:"bytes,1,opt,name=procedure,proto3" json:"procedure,omitempty"`
	// Every header as received, keyed by canonical name, after the mutations
	// of any admission service consulted before this one.
	Headers map[string]*Values `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The connection the request arrived on.
	Peer          *Peer `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmissionRequest) Reset() {
	*x = AdmissionRequest{}
	mi := &file_admission_admission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionRequest) ProtoMessage() {}

func (x *AdmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionRequest.ProtoReflect.Descriptor instead.
func (*AdmissionRequest) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{0}
}

func (x *AdmissionRequest) GetProcedure() string {
	if x != nil {
		return x.Procedure
	}
	return ""
}

func (x *AdmissionRequest) GetHeaders() map[string]*Values {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *AdmissionRequest) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

// Values is one header's values, in order.
type Values struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Values) Reset() {
	*x = Values{}
	mi := &file_admission_admission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Values) ProtoMessage() {}

func (x *Values) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Values.ProtoReflect.Descriptor instead.
func (*Values) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{1}
}

func (x *Values) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Peer describes the connection a request arrived on.
type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The remote address, host:port.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The leaf certificate the client presented, DER-encoded, when the
	// connection was TLS and the client presented one. Empty otherwise.
	Certificate   []byte `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_admission_admission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{2}
}

func (x *Peer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Peer) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

// AdmissionResponse is what the gateway changes on the forwarded request.
// remove is applied before set.
type AdmissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Headers deleted from the forwarded request, by name.
	Remove []string `protobuf:"bytes,1,rep,name=remove,proto3" json:"remove,omitempty"`
	// Headers set on the forwarded request, each replacing every existing
	// value of that name.
	Set []*Header `protobuf:"bytes,2,rep,name=set,proto3" json:"set,omitempty"`
	// The procedure the request is forwarded to in place of the one it named,
	// /package.Service/Method. Empty leaves the target as it is. The gateway
	// resolves the target after the last admission service has answered, so a
	// later service sees this as the request's procedure.
	Procedure     string `protobuf:"bytes,3,opt,name=procedure,proto3" json:"procedure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmissionResponse) Reset() {
	*x = AdmissionResponse{}
	mi := &file_admission_admission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionResponse) ProtoMessage() {}

func (x *AdmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionResponse.ProtoReflect.Descriptor instead.
func (*AdmissionResponse) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{3}
}

func (x *AdmissionResponse) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *AdmissionResponse) GetSet() []*Header {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *AdmissionResponse) GetProcedure() string {
	if x != nil {
		return x.Procedure
	}
	return ""
}

// Header is one header to set.
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_admission_admission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{4}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_admission_admission_proto protoreflect.FileDescriptor

const file_admission_admission_proto_rawDesc = "" +
	"\n" +
	"\x19admission/admission.proto\x12\tadmission\"\xe8\x01\n" +
	"\x10AdmissionRequest\x12\x1c\n" +
	"\tprocedure\x18\x01 \x01(\tR\tprocedure\x12B\n" +
	"\aheaders\x18\x02 \x03(\v2(.admission.AdmissionRequest.HeadersEntryR\aheaders\x12#\n" +
	"\x04peer\x18\x03 \x01(\v2\x0f.admission.PeerR\x04peer\x1aM\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.admission.ValuesR\x05value:\x028\x01\" \n" +
	"\x06Values\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"B\n" +
	"\x04Peer\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12 \n" +
	"\vcertificate\x18\x02 \x01(\fR\vcertificate\"n\n" +
	"\x11AdmissionResponse\x12\x16\n" +
	"\x06remove\x18\x01 \x03(\tR\x06remove\x12#\n" +
	"\x03set\x18\x02 \x03(\v2\x11.admission.HeaderR\x03set\x12\x1c\n" +
	"\tprocedure\x18\x03 \x01(\tR\tprocedure\"4\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06valuesB+Z)github.com/pbrpc/connect-protos/admissionb\x06proto3"

var (
	file_admission_admission_proto_rawDescOnce sync.Once
	file_admission_admission_proto_rawDescData []byte
)

func file_admission_admission_proto_rawDescGZIP() []byte {
	file_admission_admission_proto_rawDescOnce.Do(func() {
		file_admission_admission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admission_admission_proto_rawDesc), len(file_admission_admission_proto_rawDesc)))
	})
	return file_admission_admission_proto_rawDescData
}

var file_admission_admission_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admission_admission_proto_goTypes = []any{
	(*AdmissionRequest)(nil),  // 0: admission.AdmissionRequest
	(*Values)(nil),            // 1: admission.Values
	(*Peer)(nil),              // 2: admission.Peer
	(*AdmissionResponse)(nil), // 3: admission.AdmissionResponse
	(*Header)(nil),            // 4: admission.Header
	nil,                       // 5: admission.AdmissionRequest.HeadersEntry
}
var file_admission_admission_proto_depIdxs = []int32{
	5, // 0: admission.AdmissionRequest.headers:type_name -> admission.AdmissionRequest.HeadersEntry
	2, // 1: admission.AdmissionRequest.peer:type_name -> admission.Peer
	4, // 2: admission.AdmissionResponse.set:type_name -> admission.Header
	1, // 3: admission.AdmissionRequest.HeadersEntry.value:type_name -> admission.Values
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_admission_admission_proto_init() }
func file_admission_admission_proto_init() {
	if File_admission_admission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admission_admission_proto_rawDesc), len(file_admission_admission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admission_admission_proto_goTypes,
		DependencyIndexes: file_admission_admission_proto_depIdxs,
		MessageInfos:      file_admission_admission_proto_msgTypes,
	}.Build()
	File_admission_admission_proto = out.File
	file_admission_admission_proto_goTypes = nil
	file_admission_admission_proto_depIdxs = nil
}
