// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: diagnostics/diagnostics.proto

package diagnosticsconnect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	diagnostics "github.com/pbrpc/connect-protos/diagnostics"
	sync "sync"
)

const (
	// DiagnosticsServiceName is the fully-qualified name of the DiagnosticsService service.
	DiagnosticsServiceName = "diagnostics.DiagnosticsService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DiagnosticsServiceGetDiagnosticsProcedure is the procedure name of the DiagnosticsService's
	// GetDiagnostics RPC.
	DiagnosticsServiceGetDiagnosticsProcedure = "/diagnostics.DiagnosticsService/GetDiagnostics"
)

var (
	diagnosticsServiceGetDiagnosticsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     diagnostics.File_diagnostics_diagnostics_proto.Services().ByName("DiagnosticsService").Methods().ByName("GetDiagnostics"),
			Procedure:  DiagnosticsServiceGetDiagnosticsProcedure,
		}
	})
)

// DiagnosticsServiceClient is a client for the diagnostics.DiagnosticsService service.
type DiagnosticsServiceClient interface {
	// GetDiagnostics checks every dependency and reports each one.
	GetDiagnostics(context.Context, *diagnostics.GetDiagnosticsRequest) (*diagnostics.GetDiagnosticsResponse, error)
}

// NewDiagnosticsServiceClient constructs a client for the diagnostics.DiagnosticsService service.
// Multiple service clients may share a single connect.Client.
func NewDiagnosticsServiceClient(client *connect.Client) DiagnosticsServiceClient {
	return &diagnosticsServiceClient{client: client}
}

// DiagnosticsServiceHandler is an implementation of the diagnostics.DiagnosticsService service.
type DiagnosticsServiceHandler interface {
	// GetDiagnostics checks every dependency and reports each one.
	GetDiagnostics(context.Context, *diagnostics.GetDiagnosticsRequest) (*diagnostics.GetDiagnosticsResponse, error)
}

// RegisterDiagnosticsServiceHandler registers svc as the diagnostics.DiagnosticsService
// implementation on server.
func RegisterDiagnosticsServiceHandler(server *connect.Server, svc DiagnosticsServiceHandler) {
	adapter := diagnosticsServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: diagnosticsServiceGetDiagnosticsSpec(), Handler: adapter.getDiagnostics},
	)
}

// UnimplementedDiagnosticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDiagnosticsServiceHandler struct{}

func (UnimplementedDiagnosticsServiceHandler) GetDiagnostics(context.Context, *diagnostics.GetDiagnosticsRequest) (*diagnostics.GetDiagnosticsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "diagnostics.DiagnosticsService.GetDiagnostics is not implemented")
}

type diagnosticsServiceClient struct {
	client *connect.Client
}

func (c *diagnosticsServiceClient) GetDiagnostics(ctx context.Context, req *diagnostics.GetDiagnosticsRequest) (*diagnostics.GetDiagnosticsResponse, error) {
	var res diagnostics.GetDiagnosticsResponse
	if err := c.client.CallUnary(ctx, diagnosticsServiceGetDiagnosticsSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type diagnosticsServiceHandler struct{ svc DiagnosticsServiceHandler }

func (h diagnosticsServiceHandler) getDiagnostics(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req diagnostics.GetDiagnosticsRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetDiagnostics(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
